module.exports = {
	EVENT_CONNECTION_ESTABLISHED: 'EVENT_CONNECTION_ESTABLISHED',
	EVENT_ESTABLISH_CHANNEL: 'EVENT_ESTABLISH_CHANNEL',
	EVENT_REQUEST_SUBSCRIPTION:'EVENT_REQUEST_SUBSCRIPTION',
	EVENT_STOP_SUBSCRIPTION:'EVENT_STOP_SUBSCRIPTION',
	EVENT_ALLOW_SUBSCRIPTION: 'EVENT_ALLOW_SUBSCRIPTION',
	EVENT_DENY_SUBSCRIPTION:'EVENT_DENY_SUBSCRIPTION',
	EVENT_PUBLISH_LOCATION:'EVENT_PUBLISH_LOCATION',
	EVENT_STOP_PUBLISH:'EVENT_STOP_PUBLISH',
	EVENT_ON_LOCATION_RECEIVE:'message'
};
