export const CHANGE_VIEW = 'CHANGE_VIEW';
export const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS';
export const ACTION_TYPE_LOC_UPDATE = 'ACTION_TYPE_LOC_UPDATE';
export const REQUEST_LOCATION = 'REQUEST_LOCATION';
export const ADD_TO_SUBSCRIBER = 'ADD_TO_SUBSCRIBER';
export const SET_MY_LOCATION = 'SET_MY_LOCATION';
export const GET_PERSISTED_STATE = 'GET_PERSISTED_STATE';
export const SET_MY_CONTACT = 'SET_MY_CONTACT';