export const CHANGE_VIEW = 'CHANGE_VIEW';
export const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS';
export const ACTION_TYPE_LOC_UPDATE = 'ACTION_TYPE_LOC_UPDATE';
export const REQUEST_LOCATION = 'REQUEST_LOCATION';
export const ADD_TO_RECENT = 'ADD_TO_RECENT';